# Generated by Django 4.2.6 on 2024-05-27 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField()),
                ('course_code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesMaterials',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('material_text', models.TextField(blank=True, null=True)),
                ('material_links', models.TextField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('second_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('task', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
                ('is_chief', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsLogin',
            fields=[
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.students')),
                ('password_salt', models.CharField(max_length=256)),
                ('password_hash', models.CharField(max_length=256)),
                ('hash_algorithm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachersLogin',
            fields=[
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.teachers')),
                ('password_salt', models.CharField(max_length=256)),
                ('password_hash', models.CharField(max_length=256)),
                ('hash_algorithm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachersAchievement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('curse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='core.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='TasksMaterials',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('material_text', models.TextField(blank=True, null=True)),
                ('material_links', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_theme', to='core.themes'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teachers'),
        ),
        migrations.CreateModel(
            name='StudentsAchievement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('curse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='core.students')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('grade', models.PositiveSmallIntegerField()),
                ('answer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.answers')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_files', to='core.tasksmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='CoursesMaterialsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_files', to='core.coursesmaterials')),
            ],
        ),
        migrations.AddField(
            model_name='coursesmaterials',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_theme', to='core.themes'),
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, to='core.students'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='core.teachers'),
        ),
        migrations.CreateModel(
            name='AnswersFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_files', to='core.answers')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students'),
        ),
        migrations.AddField(
            model_name='answers',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tasks'),
        ),
    ]
